spring:
  profiles:
    active: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&amp;characterEncoding=utf8
#    username: root
#    password: 123
  druid:
    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5 #池启动时创建的连接数量
    minIdle: 5 #在不新建连接的条件下，池中保持空闲的最少连接数。
    maxActive: 20 #同一时间可以从池分配的最多连接数量。设置为0时表示无限制。
    maxWait: 10000 #在抛出异常之前，池等待连接被回收的最长时间（当没有可用连接时）。设置为-1表示无限等待。
    timeBetweenEvictionRunsMillis: 60000 #检查一次连接池中空闲的连接
    minEvictableIdleTimeMillis: 300000 #连接保持空闲而不被驱逐的最长时间
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    database: 5 # Redis数据库索引（默认为0
    host: 127.0.0.1
    port: 6379
    password: 123
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 20000 # 连接超时时间（毫秒）
