spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    database: 5 # Redis数据库索引（默认为0
    host: 127.0.0.1
    port: 6379
    password: 123
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 20000 # 连接超时时间（毫秒）
